package main

import (
	"flag"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"time"
)

// static version number, this will be autogenerated later
const version = "1.0.0"

// config options struct, this will use cli flags later
type config struct {
	port int
	env  string
}

// app struct for dep injection across the app
type application struct {
	config config
	logger *slog.Logger
}

func main() {
	// declare an instance of config to use in our app
	var cfg config

	// read the cli flags into the config struct
	// the 8080 port deviates from the 4000 port used in book
	flag.IntVar(&cfg.port, "port", 8080, "API server port")
	// the "testing" value deviates from "staging", as "testing" is more common here
	flag.StringVar(&cfg.env, "env", "development", "Environment (development|testing|production)")
	flag.Parse()

	// init logger
	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))

	// declare app object and pass in it's properties
	app := &application{
		config: cfg,
		logger: logger,
	}

	// decalare servemux and healthcheck route
	mux := http.NewServeMux()
	mux.HandleFunc("/v1/healthcheck", app.healthcheckHandler)

	// declare server
	srv := &http.Server{
		Addr:         fmt.Sprintf(":%d", cfg.port),
		Handler:      app.routes(),
		IdleTimeout:  time.Minute,
		ReadTimeout:  5 * time.Second,
		WriteTimeout: 10 * time.Second,
		ErrorLog:     slog.NewLogLogger(logger.Handler(), slog.LevelError),
	}

	// start server and logging
	logger.Info("starting server", "addr", srv.Addr, "env", cfg.env)
	err := srv.ListenAndServe()
	logger.Error(err.Error())
	os.Exit(1)
}
